# Generated by Django 2.2.12 on 2020-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200610_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(blank=True, default='defaultPost.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
