# Generated by Django 2.2.12 on 2020-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200617_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='Why this article?'),
        ),
    ]
